package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TruckAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTruckAllPropertiesEquals(Truck expected, Truck actual) {
        assertTruckAutoGeneratedPropertiesEquals(expected, actual);
        assertTruckAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTruckAllUpdatablePropertiesEquals(Truck expected, Truck actual) {
        assertTruckUpdatableFieldsEquals(expected, actual);
        assertTruckUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTruckAutoGeneratedPropertiesEquals(Truck expected, Truck actual) {
        assertThat(expected)
            .as("Verify Truck auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTruckUpdatableFieldsEquals(Truck expected, Truck actual) {
        assertThat(expected)
            .as("Verify Truck relevant properties")
            .satisfies(e -> assertThat(e.getRegionName()).as("check regionName").isEqualTo(actual.getRegionName()))
            .satisfies(e -> assertThat(e.getLicensePlate()).as("check licensePlate").isEqualTo(actual.getLicensePlate()))
            .satisfies(e -> assertThat(e.getImageUrl()).as("check imageUrl").isEqualTo(actual.getImageUrl()))
            .satisfies(e -> assertThat(e.getModel()).as("check model").isEqualTo(actual.getModel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTruckUpdatableRelationshipsEquals(Truck expected, Truck actual) {
        // empty method
    }
}
